#create mongodb secret with name mongodb-pass
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-pass
  namespace: karsajobs-ns
type: Opaque
data:
  #base64 username : admin
  MONGO_ROOT_USERNAME: YWRtaW4=
  #base64 password : supersecretpassword
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==

