#create serive for backend with name karsajobs-backend-service
apiVersion: v1
kind: Service
metadata:
  name: karsajobs-backend-service
  labels:
    app: karsajobs
spec:
  #select with label tier:backend
  selector:
    tier: backend
  ports:
    - port: 8080
  type: NodePort
