#create service for frontend with name karsajobs-ui-service
apiVersion: v1
kind: Service
metadata:
  name: karsajobs-ui-service
  labels:
    app: karsajobs
spec:
  #set selector label tier:frontend
  selector:
    tier: frontend
  ports:
    - port: 8000
  type: NodePort
